am4core.ready(function () {
    var data = [{
        'id': 'CN',
        'Country': 'China',
        'Total cases': '80,849',
        'New cases': '+25',
        'Total deaths': '3,199',
        'New deaths': '+10',
        'Total recovered': '66,931',
        'Active cases': '10,719',
        'Serious, critical': '3,226',
        'Tot cases/1M pop': '56.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IT',
        'Country': 'Italy',
        'Total cases': '24,747',
        'New cases': '+3,590',
        'Total deaths': '1,809',
        'New deaths': '+368',
        'Total recovered': '2,335',
        'Active cases': '20,603',
        'Serious, critical': '1,672',
        'Tot cases/1M pop': '409.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IR',
        'Country': 'Iran',
        'Total cases': '13,938',
        'New cases': '+1,209',
        'Total deaths': '724',
        'New deaths': '+113',
        'Total recovered': '4,590',
        'Active cases': '8,624',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '165.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'KR',
        'Country': 'S. Korea',
        'Total cases': '8,162',
        'New cases': '+76',
        'Total deaths': '75',
        'New deaths': '+3',
        'Total recovered': '834',
        'Active cases': '7,253',
        'Serious, critical': '59',
        'Tot cases/1M pop': '159.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'ES',
        'Country': 'Spain',
        'Total cases': '7,798',
        'New cases': '+1,407',
        'Total deaths': '292',
        'New deaths': '+96',
        'Total recovered': '517',
        'Active cases': '6,989',
        'Serious, critical': '272',
        'Tot cases/1M pop': '166.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'DE',
        'Country': 'Germany',
        'Total cases': '5,813',
        'New cases': '+1,214',
        'Total deaths': '11',
        'New deaths': '+2',
        'Total recovered': '46',
        'Active cases': '5,756',
        'Serious, critical': '2',
        'Tot cases/1M pop': '69.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'FR',
        'Country': 'France',
        'Total cases': '4,499',
        'New cases': '+30',
        'Total deaths': '91',
        'New deaths': 'NaN',
        'Total recovered': '12',
        'Active cases': '4,396',
        'Serious, critical': '300',
        'Tot cases/1M pop': '68.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'US',
        'Country': 'USA',
        'Total cases': '3,326',
        'New cases': '+383',
        'Total deaths': '63',
        'New deaths': '+6',
        'Total recovered': '59',
        'Active cases': '3,204',
        'Serious, critical': '10',
        'Tot cases/1M pop': '10.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CH',
        'Country': 'Switzerland',
        'Total cases': '2,217',
        'New cases': '+842',
        'Total deaths': '14',
        'New deaths': '+1',
        'Total recovered': '4',
        'Active cases': '2,199',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '256.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GB',
        'Country': 'UK',
        'Total cases': '1,372',
        'New cases': '+232',
        'Total deaths': '35',
        'New deaths': '+14',
        'Total recovered': '20',
        'Active cases': '1,317',
        'Serious, critical': '20',
        'Tot cases/1M pop': '20.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NO',
        'Country': 'Norway',
        'Total cases': '1,231',
        'New cases': '+122',
        'Total deaths': '3',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '1,227',
        'Serious, critical': '27',
        'Tot cases/1M pop': '227.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NL',
        'Country': 'Netherlands',
        'Total cases': '1,135',
        'New cases': '+176',
        'Total deaths': '20',
        'New deaths': '+8',
        'Total recovered': '2',
        'Active cases': '1,113',
        'Serious, critical': '45',
        'Tot cases/1M pop': '66.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SE',
        'Country': 'Sweden',
        'Total cases': '1,024',
        'New cases': '+63',
        'Total deaths': '3',
        'New deaths': '+1',
        'Total recovered': '1',
        'Active cases': '1,020',
        'Serious, critical': '2',
        'Tot cases/1M pop': '101.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BE',
        'Country': 'Belgium',
        'Total cases': '886',
        'New cases': '+197',
        'Total deaths': '4',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '881',
        'Serious, critical': '33',
        'Tot cases/1M pop': '76.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'DK',
        'Country': 'Denmark',
        'Total cases': '864',
        'New cases': '+28',
        'Total deaths': '2',
        'New deaths': '+1',
        'Total recovered': '1',
        'Active cases': '861',
        'Serious, critical': '2',
        'Tot cases/1M pop': '149.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AT',
        'Country': 'Austria',
        'Total cases': '860',
        'New cases': '+205',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': '6',
        'Active cases': '853',
        'Serious, critical': '1',
        'Tot cases/1M pop': '95.5',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'JP',
        'Country': 'Japan',
        'Total cases': '839',
        'New cases': '+35',
        'Total deaths': '24',
        'New deaths': '+2',
        'Total recovered': '144',
        'Active cases': '671',
        'Serious, critical': '36',
        'Tot cases/1M pop': '6.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NaN',
        'Country': 'Diamond Princess',
        'Total cases': '696',
        'New cases': 'NaN',
        'Total deaths': '7',
        'New deaths': 'NaN',
        'Total recovered': '456',
        'Active cases': '233',
        'Serious, critical': '15',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MY',
        'Country': 'Malaysia',
        'Total cases': '428',
        'New cases': '+190',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '42',
        'Active cases': '386',
        'Serious, critical': '9',
        'Tot cases/1M pop': '13.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'QA',
        'Country': 'Qatar',
        'Total cases': '401',
        'New cases': '+64',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '4',
        'Active cases': '397',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '139.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GR',
        'Country': 'Greece',
        'Total cases': '331',
        'New cases': '+103',
        'Total deaths': '4',
        'New deaths': '+1',
        'Total recovered': '8',
        'Active cases': '319',
        'Serious, critical': '5',
        'Tot cases/1M pop': '31.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CA',
        'Country': 'Canada',
        'Total cases': '317',
        'New cases': '+65',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': '11',
        'Active cases': '305',
        'Serious, critical': '1',
        'Tot cases/1M pop': '8.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AU',
        'Country': 'Australia',
        'Total cases': '300',
        'New cases': '+52',
        'Total deaths': '5',
        'New deaths': '+2',
        'Total recovered': '27',
        'Active cases': '268',
        'Serious, critical': '1',
        'Tot cases/1M pop': '11.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CZ',
        'Country': 'Czechia',
        'Total cases': '253',
        'New cases': '+64',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '253',
        'Serious, critical': '2',
        'Tot cases/1M pop': '23.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PT',
        'Country': 'Portugal',
        'Total cases': '245',
        'New cases': '+76',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '243',
        'Serious, critical': '9',
        'Tot cases/1M pop': '24.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'FI',
        'Country': 'Finland',
        'Total cases': '244',
        'New cases': '+19',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '10',
        'Active cases': '234',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '44.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SG',
        'Country': 'Singapore',
        'Total cases': '226',
        'New cases': '+14',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '105',
        'Active cases': '121',
        'Serious, critical': '11',
        'Tot cases/1M pop': '38.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SI',
        'Country': 'Slovenia',
        'Total cases': '219',
        'New cases': '+38',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '218',
        'Serious, critical': '3',
        'Tot cases/1M pop': '105.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BH',
        'Country': 'Bahrain',
        'Total cases': '214',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '60',
        'Active cases': '154',
        'Serious, critical': '2',
        'Tot cases/1M pop': '125.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IL',
        'Country': 'Israel',
        'Total cases': '213',
        'New cases': '+20',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '4',
        'Active cases': '209',
        'Serious, critical': '2',
        'Tot cases/1M pop': '24.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'EE',
        'Country': 'Estonia',
        'Total cases': '171',
        'New cases': '+56',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '170',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '128.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IS',
        'Country': 'Iceland',
        'Total cases': '171',
        'New cases': '+10',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '171',
        'Serious, critical': '1',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IE',
        'Country': 'Ireland',
        'Total cases': '169',
        'New cases': '+40',
        'Total deaths': '2',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '166',
        'Serious, critical': '6',
        'Tot cases/1M pop': '34.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'HK',
        'Country': 'Hong Kong',
        'Total cases': '149',
        'New cases': '+7',
        'Total deaths': '4',
        'New deaths': 'NaN',
        'Total recovered': '81',
        'Active cases': '64',
        'Serious, critical': '4',
        'Tot cases/1M pop': '19.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PH',
        'Country': 'Philippines',
        'Total cases': '140',
        'New cases': '+29',
        'Total deaths': '11',
        'New deaths': '+3',
        'Total recovered': '2',
        'Active cases': '127',
        'Serious, critical': '1',
        'Tot cases/1M pop': '1.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'RO',
        'Country': 'Romania',
        'Total cases': '139',
        'New cases': '+16',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '9',
        'Active cases': '130',
        'Serious, critical': '1',
        'Tot cases/1M pop': '7.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PL',
        'Country': 'Poland',
        'Total cases': '123',
        'New cases': '+19',
        'Total deaths': '3',
        'New deaths': 'NaN',
        'Total recovered': '13',
        'Active cases': '107',
        'Serious, critical': '3',
        'Tot cases/1M pop': '3.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BR',
        'Country': 'Brazil',
        'Total cases': '121',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '120',
        'Serious, critical': '2',
        'Tot cases/1M pop': '0.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'ID',
        'Country': 'Indonesia',
        'Total cases': '117',
        'New cases': '+21',
        'Total deaths': '5',
        'New deaths': 'NaN',
        'Total recovered': '8',
        'Active cases': '104',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IQ',
        'Country': 'Iraq',
        'Total cases': '116',
        'New cases': '+6',
        'Total deaths': '10',
        'New deaths': 'NaN',
        'Total recovered': '26',
        'Active cases': '80',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '2.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'TH',
        'Country': 'Thailand',
        'Total cases': '114',
        'New cases': '+32',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': '35',
        'Active cases': '78',
        'Serious, critical': '1',
        'Tot cases/1M pop': '1.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'KW',
        'Country': 'Kuwait',
        'Total cases': '112',
        'New cases': '+8',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '9',
        'Active cases': '103',
        'Serious, critical': '4',
        'Tot cases/1M pop': '26.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'IN',
        'Country': 'India',
        'Total cases': '111',
        'New cases': '+11',
        'Total deaths': '2',
        'New deaths': 'NaN',
        'Total recovered': '13',
        'Active cases': '96',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'EG',
        'Country': 'Egypt',
        'Total cases': '110',
        'New cases': 'NaN',
        'Total deaths': '2',
        'New deaths': 'NaN',
        'Total recovered': '27',
        'Active cases': '81',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SA',
        'Country': 'Saudi Arabia',
        'Total cases': '103',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '101',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '3.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SM',
        'Country': 'San Marino',
        'Total cases': '101',
        'New cases': 'NaN',
        'Total deaths': '5',
        'New deaths': 'NaN',
        'Total recovered': '4',
        'Active cases': '92',
        'Serious, critical': '3',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LB',
        'Country': 'Lebanon',
        'Total cases': '99',
        'New cases': '+6',
        'Total deaths': '3',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '95',
        'Serious, critical': '3',
        'Tot cases/1M pop': '14.5',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AE',
        'Country': 'UAE',
        'Total cases': '98',
        'New cases': '+13',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '20',
        'Active cases': '78',
        'Serious, critical': '2',
        'Tot cases/1M pop': '9.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CL',
        'Country': 'Chile',
        'Total cases': '75',
        'New cases': '+14',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '75',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '3.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'RU',
        'Country': 'Russia',
        'Total cases': '63',
        'New cases': '+4',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '8',
        'Active cases': '55',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'ZA',
        'Country': 'South Africa',
        'Total cases': '61',
        'New cases': '+23',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '61',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LU',
        'Country': 'Luxembourg',
        'Total cases': '59',
        'New cases': '+8',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '58',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'TW',
        'Country': 'Taiwan',
        'Total cases': '59',
        'New cases': '+6',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': '20',
        'Active cases': '38',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '2.5',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'VN',
        'Country': 'Vietnam',
        'Total cases': '56',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '16',
        'Active cases': '40',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SK',
        'Country': 'Slovakia',
        'Total cases': '54',
        'New cases': '+10',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '54',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '9.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PK',
        'Country': 'Pakistan',
        'Total cases': '53',
        'New cases': '+20',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '51',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BG',
        'Country': 'Bulgaria',
        'Total cases': '51',
        'New cases': '+10',
        'Total deaths': '2',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '49',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '7.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BN',
        'Country': 'Brunei',
        'Total cases': '50',
        'New cases': '+10',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '50',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'HR',
        'Country': 'Croatia',
        'Total cases': '49',
        'New cases': '+10',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '47',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '11.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'DZ',
        'Country': 'Algeria',
        'Total cases': '48',
        'New cases': '+9',
        'Total deaths': '4',
        'New deaths': '+1',
        'Total recovered': '10',
        'Active cases': '34',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'RS',
        'Country': 'Serbia',
        'Total cases': '48',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '47',
        'Serious, critical': '1',
        'Tot cases/1M pop': '5.5',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AR',
        'Country': 'Argentina',
        'Total cases': '45',
        'New cases': 'NaN',
        'Total deaths': '2',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '43',
        'Serious, critical': '1',
        'Tot cases/1M pop': '1.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PA',
        'Country': 'Panama',
        'Total cases': '43',
        'New cases': 'NaN',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '42',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '10.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PE',
        'Country': 'Peru',
        'Total cases': '43',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '43',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AL',
        'Country': 'Albania',
        'Total cases': '42',
        'New cases': '+4',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '41',
        'Serious, critical': '2',
        'Tot cases/1M pop': '14.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MX',
        'Country': 'Mexico',
        'Total cases': '41',
        'New cases': '+15',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '4',
        'Active cases': '37',
        'Serious, critical': '1',
        'Tot cases/1M pop': '0.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PS',
        'Country': 'Palestine',
        'Total cases': '38',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '38',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '7.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CO',
        'Country': 'Colombia',
        'Total cases': '34',
        'New cases': '+10',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '34',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GE',
        'Country': 'Georgia',
        'Total cases': '33',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '32',
        'Serious, critical': '1',
        'Tot cases/1M pop': '8.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CY',
        'Country': 'Cyprus',
        'Total cases': '33',
        'New cases': '+7',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '33',
        'Serious, critical': '1',
        'Tot cases/1M pop': '27.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'HU',
        'Country': 'Hungary',
        'Total cases': '32',
        'New cases': '+2',
        'Total deaths': '1',
        'New deaths': '+1',
        'Total recovered': '1',
        'Active cases': '30',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '3.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LV',
        'Country': 'Latvia',
        'Total cases': '30',
        'New cases': '+4',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '29',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '15.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'EC',
        'Country': 'Ecuador',
        'Total cases': '28',
        'New cases': 'NaN',
        'Total deaths': '2',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '26',
        'Serious, critical': '1',
        'Tot cases/1M pop': '1.6',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MA',
        'Country': 'Morocco',
        'Total cases': '28',
        'New cases': '+10',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '26',
        'Serious, critical': '1',
        'Tot cases/1M pop': '0.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BY',
        'Country': 'Belarus',
        'Total cases': '27',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '3',
        'Active cases': '24',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '2.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CR',
        'Country': 'Costa Rica',
        'Total cases': '27',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '27',
        'Serious, critical': '1',
        'Tot cases/1M pop': '5.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AM',
        'Country': 'Armenia',
        'Total cases': '26',
        'New cases': '+6',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '26',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '8.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SN',
        'Country': 'Senegal',
        'Total cases': '24',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '22',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BA',
        'Country': 'Bosnia and Herzegovina',
        'Total cases': '24',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '24',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '7.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AZ',
        'Country': 'Azerbaijan',
        'Total cases': '23',
        'New cases': '+4',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': '6',
        'Active cases': '16',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '2.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MD',
        'Country': 'Moldova',
        'Total cases': '23',
        'New cases': '+11',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '23',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '5.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'OM',
        'Country': 'Oman',
        'Total cases': '22',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '9',
        'Active cases': '13',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '4.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MT',
        'Country': 'Malta',
        'Total cases': '21',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '19',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'TN',
        'Country': 'Tunisia',
        'Total cases': '20',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '20',
        'Serious, critical': '2',
        'Tot cases/1M pop': '1.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MK',
        'Country': 'North Macedonia',
        'Total cases': '19',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '18',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '9.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LK',
        'Country': 'Sri Lanka',
        'Total cases': '18',
        'New cases': '+8',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '17',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AF',
        'Country': 'Afghanistan',
        'Total cases': '16',
        'New cases': '+5',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '15',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MV',
        'Country': 'Maldives',
        'Total cases': '13',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '13',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'KH',
        'Country': 'Cambodia',
        'Total cases': '12',
        'New cases': '+5',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '11',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LT',
        'Country': 'Lithuania',
        'Total cases': '12',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '11',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '4.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MO',
        'Country': 'Macao',
        'Total cases': '11',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '10',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'DO',
        'Country': 'Dominican Republic',
        'Total cases': '11',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '11',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'FO',
        'Country': 'Faeroe Islands',
        'Total cases': '11',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '11',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'JO',
        'Country': 'Jordan',
        'Total cases': '10',
        'New cases': '+9',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '9',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BO',
        'Country': 'Bolivia',
        'Total cases': '10',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '10',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'JM',
        'Country': 'Jamaica',
        'Total cases': '10',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '8',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '3.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MQ',
        'Country': 'Martinique',
        'Total cases': '10',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '10',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'VE',
        'Country': 'Venezuela',
        'Total cases': '10',
        'New cases': '+8',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '10',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'KZ',
        'Country': 'Kazakhstan',
        'Total cases': '9',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '9',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.5',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NZ',
        'Country': 'New Zealand',
        'Total cases': '8',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '8',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GF',
        'Country': 'French Guiana',
        'Total cases': '7',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '7',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LI',
        'Country': 'Liechtenstein',
        'Total cases': '7',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '7',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PY',
        'Country': 'Paraguay',
        'Total cases': '7',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '7',
        'Serious, critical': '1',
        'Tot cases/1M pop': '1.0',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'RE',
        'Country': 'Réunion',
        'Total cases': '7',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '7',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GH',
        'Country': 'Ghana',
        'Total cases': '6',
        'New cases': '+4',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '6',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'TR',
        'Country': 'Turkey',
        'Total cases': '6',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '6',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'UY',
        'Country': 'Uruguay',
        'Total cases': '6',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '6',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AD',
        'Country': 'Andorra',
        'Total cases': '5',
        'New cases': '+4',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '5',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BD',
        'Country': 'Bangladesh',
        'Total cases': '5',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '2',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GY',
        'Country': 'Guyana',
        'Total cases': '4',
        'New cases': '+3',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CI',
        'Country': 'Ivory Coast',
        'Total cases': '4',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '4',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CU',
        'Country': 'Cuba',
        'Total cases': '4',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '4',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'ET',
        'Country': 'Ethiopia',
        'Total cases': '4',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '4',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PR',
        'Country': 'Puerto Rico',
        'Total cases': '4',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '4',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'UA',
        'Country': 'Ukraine',
        'Total cases': '3',
        'New cases': 'NaN',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BF',
        'Country': 'Burkina Faso',
        'Total cases': '3',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NaN',
        'Country': 'Channel Islands',
        'Total cases': '3',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'PF',
        'Country': 'French Polynesia',
        'Total cases': '3',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GP',
        'Country': 'Guadeloupe',
        'Total cases': '3',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GU',
        'Country': 'Guam',
        'Total cases': '3',
        'New cases': '+3',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'HN',
        'Country': 'Honduras',
        'Total cases': '3',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'KE',
        'Country': 'Kenya',
        'Total cases': '3',
        'New cases': '+2',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SC',
        'Country': 'Seychelles',
        'Total cases': '3',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '3',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MC',
        'Country': 'Monaco',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NG',
        'Country': 'Nigeria',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AW',
        'Country': 'Aruba',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CM',
        'Country': 'Cameroon',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CW',
        'Country': 'Curaçao',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CD',
        'Country': 'DRC',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NA',
        'Country': 'Namibia',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.8',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'LC',
        'Country': 'Saint Lucia',
        'Total cases': '2',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MF',
        'Country': 'Saint Martin',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'TT',
        'Country': 'Trinidad and Tobago',
        'Total cases': '2',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '2',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '1.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SD',
        'Country': 'Sudan',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': '1',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '0',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'NP',
        'Country': 'Nepal',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '0',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'AG',
        'Country': 'Antigua and Barbuda',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BS',
        'Country': 'Bahamas',
        'Total cases': '1',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BT',
        'Country': 'Bhutan',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'KY',
        'Country': 'Cayman Islands',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CF',
        'Country': 'CAR',
        'Total cases': '1',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'CG',
        'Country': 'Congo',
        'Total cases': '1',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GQ',
        'Country': 'Equatorial Guinea',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.7',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GA',
        'Country': 'Gabon',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.4',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GI',
        'Country': 'Gibraltar',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': '1',
        'Active cases': '0',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GT',
        'Country': 'Guatemala',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'GN',
        'Country': 'Guinea',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'VA',
        'Country': 'Vatican City',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MR',
        'Country': 'Mauritania',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.2',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'YT',
        'Country': 'Mayotte',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'MN',
        'Country': 'Mongolia',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.3',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'RW',
        'Country': 'Rwanda',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'BL',
        'Country': 'St. Barth',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'VC',
        'Country': 'St. Vincent Grenadines',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SR',
        'Country': 'Suriname',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'SZ',
        'Country': 'Eswatini',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.9',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'TG',
        'Country': 'Togo',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': '0.1',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'VI',
        'Country': 'U.S. Virgin Islands',
        'Total cases': '1',
        'New cases': 'NaN',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    },
    {
        'id': 'UZ',
        'Country': 'Uzbekistan',
        'Total cases': '1',
        'New cases': '+1',
        'Total deaths': 'NaN',
        'New deaths': 'NaN',
        'Total recovered': 'NaN',
        'Active cases': '1',
        'Serious, critical': 'NaN',
        'Tot cases/1M pop': 'NaN',
        'fill': am4core.color('#A93226')
    }
    ]

    console.log(data.fill)
    // Themes begin
    am4core.useTheme(am4themes_dataviz);
    am4core.useTheme(am4themes_animated);
    // Themes end

    // Create map instance
    var chart = am4core.create("chartdiv", am4maps.MapChart);

    // Set map definition
    chart.geodata = am4geodata_worldLow;

    // Set projection
    chart.projection = new am4maps.projections.Miller();

    // Create map polygon series
    var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());

    // Make map load polygon (like country names) data from GeoJSON
    polygonSeries.useGeodata = true;

    // Configure series
    var polygonTemplate = polygonSeries.mapPolygons.template;

    // background color
    chart.background.fill = am4core.color("#AED6F1");
    chart.background.fillOpacity = 1;
    polygonTemplate.fill = am4core.color("#34495E");
    polygonTemplate.tooltipText =
    `{Country} 
    Total cases: {Total cases},
    New cases: {New cases},
    Total deaths: {Total deaths},
    New deaths: {New deaths},
    Total recovered: {Total recovered},
    Active cases: {Active cases},
    Serious, critical: {Serious, critical},
    Tot cases/1M pop: {Tot cases/1M pop}
    `;


    // Create hover state and set alternative fill color
    var hs = polygonTemplate.states.create("hover");
    hs.properties.fill = am4core.color("#CD6155");

    // Remove Antarctica
    polygonSeries.exclude = ["AQ"];

    // Add some data
    polygonSeries.data = data;
    // polygonSeries.data = [{
    //     fill: am4core.color("#A93226");
    // }];

    // Bind "fill" property to "fill" key in data
    polygonTemplate.propertyFields.fill = "fill";

});


